services:
  mitapi:
      build:
        context: ./mitapi
        dockerfile: Dockerfile
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./mitapi/:/usr/src/app/
      ports:
        - 8000:8000
      env_file:
        - ./.env
      # depends_on:
      #   - db
      # links:
      #   - db:db

  db:
    image: postgres:14.0-alpine
    restart: always 
    volumes:
      - ./data/postgres_data14:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hello_django_dev
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
    ports:
      - "5432:5432"

  # pgadmin:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4
  #   restart: always
  #   volumes:
  #     - ./data/pgadmin-data:/var/lib/pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: root@root.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #     # PGADMIN_LISTEN_PORT = 80
  #   ports:
  #     - "5050:80"
  #   networks:
  #     app_net:
  #       ipv4_address: 192.168.0.3

# networks:
#   app_net:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 192.168.100.0/24

# volumes:
#   postgres_data: